version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      # Group all npm dependencies together
      all-dependencies:
        patterns:
          - '*'
    open-pull-requests-limit: 10
