shellEmulator: true
trustPolicy: no-downgrade

packages:
  - packages/*

overrides:
  vite: npm:rolldown-vite@latest

defines:
  - &vue ^3.6.0-beta.3
  - &vue-lang-tools 3.0.3
  - &volar-libs 2.4.20
  - &volar-services 0.0.65

catalogs:
  cli:
    '@changesets/cli': ^2.29.8
    '@clack/prompts': ^0.11.0
    clerc: ^1.2.1
    consola: ^3.4.2
    debug: ^4.4.3
    del: ^8.0.1
    execa: ^9.6.1
    lint-staged: ^16.2.7
    ovsx: latest
    pkg-dir: ^9.0.0
    rollup: ^4.56.0
    simple-git-hooks: ^2.13.1
    tree-kill: ^1.2.2
    tsdown: ^0.16.8
    tsx: ^4.21.0
    typescript: ~5.9.3
    yoctocolors: ^2.1.2
  compiler:
    '@babel/parser': ^7.28.6
    '@babel/types': ^7.28.6
    '@typescript/native-preview': 7.0.0-dev.20250722.1
    estree-walker: ^3.0.3
    get-tsconfig: ^4.13.0
    magic-string: ^0.30.21
    merge-source-map: ^1.1.0
    postcss: ^8.5.6
    postcss-selector-parser: ^7.1.1
    source-map-js: ^1.2.1
    ts-morph: ^27.0.2
  docs:
    oxc-minify: ^0.99.0
    shiki: ^3.21.0
    vitepress: ^2.0.0-alpha.15
    vitepress-plugin-group-icons: ^1.7.1
  icons:
    '@iconify-json/carbon': ^1.2.18
    '@iconify-json/logos': ^1.2.10
    '@iconify-json/mdi': ^1.2.3
    '@iconify-json/twemoji': ^1.2.5
  lint-libs:
    '@antfu/eslint-config': ^6.7.3
    '@stylistic/eslint-plugin': ^5.7.0
    '@typescript-eslint/parser': ~8.48.1
    '@typescript-eslint/scope-manager': ~8.48.1
    '@typescript-eslint/types': ~8.48.1
    '@typescript-eslint/typescript-estree': ~8.48.1
    '@typescript-eslint/utils': ~8.48.1
    eslint: ~9.39.2
    eslint-scope: ^9.1.0
    eslint-vitest-rule-tester: ^3.0.1
    espree: ^11.1.0
    prettier: ^3.8.1
    prettier-linter-helpers: ^1.0.1
  miscs:
    '@umami/node': ^0.4.0
    element-plus: ^2.13.1
    make-synchronized: ^0.8.0
  nuxt-libs:
    '@nuxt/devtools': ^3.1.1
    '@nuxt/eslint-config': ^1.12.1
    '@nuxt/kit': ~4.2.2
    '@nuxt/module-builder': ^1.0.2
    '@nuxt/schema': ~4.2.2
    '@nuxt/test-utils': ^3.23.0
    nuxt: ~4.2.2
    vitest: 3.2.4 # @nuxt/test-utils requires Vitest v3
  rsstack:
    '@rsbuild/core': ^1.7.2
    '@rsbuild/plugin-sass': ^1.4.1
    '@rspack/core': ^1.7.3
  styles:
    sass: ^1.97.3
    tailwindcss: ^4.1.18
    unocss: ^66.6.0
  types:
    '@types/debug': ^4.1.12
    '@types/eslint': ^9.6.1
    '@types/estree': ^1.0.8
    '@types/hash-sum': ^1.0.2
    '@types/jsdom': ^27.0.0
    '@types/line-column': ^1.0.2
    '@types/lodash': ^4.17.23
    '@types/node': ^24.10.9
    '@types/prettier-linter-helpers': ^1.0.4
    '@types/semver': ^7.7.1
    '@types/vscode': ~1.106.1
    '@types/ws': ^8.18.1
  utils:
    '@antfu/utils': ^9.3.0
    '@baiwusanyu/utils-log': ^1.1.2
    '@changesets/changelog-github': ^0.5.2
    changelogen: ^0.6.2
    hash-sum: ^2.0.0
    line-column: ^1.0.2
    lodash: ^4.17.23
    lru-cache: ^11.2.4
    muggle-string: ^0.4.1
    semver: ^7.7.3
    yaml: ^2.8.2
  vite-ecosystem:
    '@tailwindcss/vite': ^4.1.18
    '@vitejs/plugin-vue': ^6.0.3
    '@vitejs/plugin-vue-jsx': ^5.1.3
    rolldown: latest
    rolldown-vite: latest
    unplugin-auto-import: ^20.3.0
    vite: ^7.3.1
    vite-plugin-inspect: ^11.3.3
  vitest-libs:
    jsdom: ^27.4.0
    playwright-chromium: ^1.57.0
    # eslint-disable-next-line pnpm/yaml-no-duplicate-catalog-item
    vitest: ^4.0.18 # For the rest of this repository, we use the newer version of Vitest
  volar:
    '@volar/language-core': *volar-libs
    '@volar/language-server': *volar-libs
    '@volar/language-service': *volar-libs
    '@volar/typescript': *volar-libs
    '@volar/vscode': *volar-libs
    volar-service-css: *volar-services
    volar-service-emmet: *volar-services
    volar-service-html: *volar-services
    volar-service-typescript: *volar-services
  vscode:
    '@vscode/vsce': latest
    reactive-vscode: ^0.4.1
    vscode-css-languageservice: ^6.3.9
    vscode-html-languageservice: ^5.6.1
    vscode-languageserver-protocol: ^3.17.5
    vscode-languageserver-textdocument: ^1.0.12
    vscode-uri: ^3.1.0
  vue-libs:
    '@vue/compiler-core': *vue
    '@vue/compiler-dom': *vue
    '@vue/compiler-ssr': *vue
    '@vue/compiler-vapor': *vue
    '@vue/language-core': *vue-lang-tools
    '@vue/language-service': *vue-lang-tools
    '@vue/shared': *vue
    '@vue/test-utils': ^2.4.6
    '@vueuse/core': ^14.1.0
    pinia: ^3.0.4
    vue: *vue
    vue-router: ^4.6.4
    vue-tsc: *vue-lang-tools

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - '@vscode/vsce-sign'
  - core-js
  - esbuild
  - keytar
  - playwright-chromium
  - simple-git-hooks
  - unrs-resolver
  - vue-demi
