shellEmulator: true
packages:
  - packages/*

defines:
  - &vue ^3.5.13
  - &vue-lang-tools ~2.2.10
  - &volar ~2.4.14
  - &volar-service ~0.0.64

catalogs:
  cli:
    '@changesets/cli': ^2.29.2
    '@clack/prompts': ^0.10.1
    clerc: ^0.44.0
    consola: ^3.4.2
    debug: ^4.4.0
    del: ^8.0.0
    execa: ^9.5.2
    lint-staged: ^15.5.1
    ovsx: latest
    pkg-dir: ^8.0.0
    rollup: ^4.40.0
    simple-git-hooks: ^2.13.0
    tree-kill: ^1.2.2
    tsdown: ^0.11.11
    tsx: ^4.19.3
    typescript: ~5.8.3
    yoctocolors: ^2.1.1
  compiler:
    '@babel/parser': ^7.27.0
    '@babel/types': ^7.27.0
    estree-walker: ^3.0.3
    get-tsconfig: ^4.10.0
    magic-string: ^0.30.17
    merge-source-map: ^1.1.0
    postcss: ^8.5.3
    postcss-selector-parser: ^7.1.0
    source-map-js: ^1.2.1
    ts-morph: ^25.0.1
  docs:
    '@iconify-json/logos': ^1.1.34
    '@iconify-json/twemoji': ^1.1.15
    vitepress: ^1.0.2
  lint-libs:
    '@antfu/eslint-config': ^4.12.0
    '@typescript-eslint/parser': ~8.31.0
    '@typescript-eslint/scope-manager': ~8.31.0
    '@typescript-eslint/types': ~8.31.0
    '@typescript-eslint/typescript-estree': ~8.31.0
    '@typescript-eslint/utils': ~8.31.0
    eslint: ~9.25.1
    eslint-scope: ^8.3.0
    eslint-visitor-keys: ^4.2.0
    eslint-vitest-rule-tester: ^2.2.0
    espree: ^10.3.0
    prettier: ^3.5.3
    prettier-linter-helpers: ^1.0.0
  miscs:
    element-plus: ^2.9.10
    synckit: ^0.9.2
    ws: ^8.18.1
  nuxt-libs:
    '@nuxt/devtools': ^2.4.0
    '@nuxt/eslint-config': ^1.3.0
    '@nuxt/kit': ^3.16.2
    '@nuxt/module-builder': ^1.0.1
    '@nuxt/schema': ^3.16.2
    '@nuxt/test-utils': ^3.17.2
    nuxt: ^3.16.2
  styles:
    '@iconify-json/carbon': ^1.1.20
    less: ^4.2.0
    tailwindcss: ^4.1.7
    unocss: ^66.1.2
  types:
    '@types/debug': ^4.1.12
    '@types/eslint': ^9.6.1
    '@types/estree': ^1.0.7
    '@types/hash-sum': ^1.0.2
    '@types/jsdom': ^21.1.7
    '@types/line-column': ^1.0.2
    '@types/lodash': ^4.17.16
    '@types/node': ^22.15.0
    '@types/prettier-linter-helpers': ^1.0.4
    '@types/semver': ^7.7.0
    '@types/vscode': ~1.99.1
    '@types/ws': ^8.18.1
  utils:
    '@antfu/utils': ^0.7.10
    '@baiwusanyu/utils-log': ^1.1.2
    '@changesets/changelog-github': ^0.5.1
    changelogen: ^0.6.1
    destr: ^2.0.5
    detect-port: ^2.1.0
    hash-sum: ^2.0.0
    line-column: ^1.0.2
    lodash: ^4.17.21
    lru-cache: ^11.1.0
    muggle-string: ^0.4.1
    pathe: ^2.0.3
    semver: ^7.7.1
    yaml: ^2.7.1
  vite-ecosystem:
    '@tailwindcss/vite': ^4.1.7
    '@vitejs/plugin-vue': ^5.2.3
    '@vitejs/plugin-vue-jsx': ^4.1.2
    unplugin-auto-import: ^19.1.2
    vite: ^6.3.3
    vite-plugin-inspect: ^11.0.1
  vitest-libs:
    jsdom: ^26.1.0
    playwright-chromium: ^1.52.0
    vitest: ^3.1.2
  volar:
    '@volar/language-core': *volar
    '@volar/language-server': *volar
    '@volar/language-service': *volar
    '@volar/typescript': *volar
    '@volar/vscode': *volar
    volar-service-css: *volar-service
    volar-service-emmet: *volar-service
    volar-service-html: *volar-service
    volar-service-typescript: *volar-service
  vscode:
    '@vscode/vsce': latest
    reactive-vscode: ^0.2.14
    vscode-html-languageservice: ^5.3.3
    vscode-languageserver-protocol: ^3.17.5
    vscode-languageserver-textdocument: ^1.0.12
    vscode-uri: ^3.1.0
  vue-libs:
    '@vue/compiler-dom': *vue
    '@vue/compiler-ssr': *vue
    '@vue/language-core': *vue-lang-tools
    '@vue/language-service': *vue-lang-tools
    '@vue/shared': *vue
    '@vue/test-utils': ^2.4.6
    vue: *vue
    vue-tsc: *vue-lang-tools

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - '@vscode/vsce-sign'
  - esbuild
  - keytar
  - playwright-chromium
  - simple-git-hooks
  - unrs-resolver
  - vue-demi
